### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by sunloverz** [bm-software/angular-calendar-scheduler#6]

**Comment by bm-software** [comment]
@sunloverz What do you mean? I'll close this for now. Please, if you're experiencing any problem open a more detailed issue, thank you very much :)

**Comment by sunloverz** [comment]
It doesn't work with angular 6.1

```
ERROR in src/app/reservations/reservations.component.ts(2,10): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'CalendarSchedulerEventAction'.
src/app/reservations/reservations.component.ts(2,40): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'CalendarSchedulerEvent'.
src/app/reservations/reservations.component.ts(2,64): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'SchedulerViewDay'.
src/app/reservations/reservations.component.ts(3,11): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'SchedulerViewHour'.
src/app/reservations/reservations.component.ts(3,30): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'SchedulerViewHourSegment'.
src/app/reservations/reservations.component.ts(3,56): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'subPeriod'.
src/app/reservations/reservations.component.ts(3,67): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'addPeriod'.
src/app/reservations/reservations.component.ts(3,78): error TS2305: Module '"/home/tyler/renting/node_modules/angular-calendar/angular-calendar"' has no exported member 'endOfPeriod'.
src/app/reservations/reservations.component.ts(17,11): error TS2304: Cannot find name 'CalendarPeriod'.
src/app/reservations/reservations.component.ts(30,21): error TS2304: Cannot find name 'endOfDay'.
src/app/reservations/reservations.component.ts(30,30): error TS2304: Cannot find name 'addMonths'.
src/app/reservations/reservations.component.ts(58,72): error TS2304: Cannot find name 'AppService'.
src/app/reservations/reservations.component.ts(91,22): error TS2304: Cannot find name 'CalendarPeriod'.
src/app/reservations/reservations.component.ts(141,14): error TS2339: Property 'refresh' does not exist on type 'ReservationsComponent'.
```

**Comment by sunloverz** [comment]
![screenshot from 2018-12-06 15-07-48](https://user-images.githubusercontent.com/1597561/49573659-c01f6c80-f968-11e8-9816-b4e1b3ec9b5f.png)

**Comment by bm-software** [comment]
@sunloverz Sorry, readme is not updated, I wll update it now. However you have to use `CalendarView` 
 (part of `angular-calendar` library) instead of `CalendarPeriod`.

Moreover you've imported my component from `angular-calendar` but you must import them from `angular-calendar-scheduler` :)

Let me know if the issue is solved after that fixes.
Thank you
